import Link from 'next/link'

export const metadata = {
  title: 'Terms of Service — Operator',
}

export default function TermsPage() {
  return (
    <main className="min-h-screen" style={{ background: 'var(--background)', color: 'var(--foreground)' }}>
      <nav className="flex items-center justify-between px-6 py-5 max-w-3xl mx-auto">
        <Link href="/" className="text-sm font-semibold tracking-[0.2em] uppercase" style={{ color: 'var(--accent)', textDecoration: 'none' }}>
          Operator
        </Link>
        <span className="text-xs" style={{ color: 'var(--muted)' }}>by AIGA LLC</span>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-12">
        <p className="text-xs tracking-widest uppercase mb-4" style={{ color: 'var(--accent)' }}>Legal</p>
        <h1 className="text-4xl font-bold mb-3">Terms of Service</h1>
        <p className="text-sm mb-12" style={{ color: 'var(--muted)' }}>Effective date: April 24, 2026 · AIGA LLC</p>

        <div className="space-y-10 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold mb-3">The service</h2>
            <p style={{ color: 'var(--muted)' }}>
              Operator is a conversational AI learning platform operated by AIGA LLC. It provides structured, conversation-based lessons on using AI tools effectively, delivered through an AI teacher named Gojo. By signing up, you agree to these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Access</h2>
            <ul className="space-y-2" style={{ color: 'var(--muted)' }}>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> The course — 6 conversation lessons — is currently free with email signup.</li>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> We may add paid offerings in the future (for example, team or business versions). Any such change will not remove free access to the lessons you signed up for.</li>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> Access is non-transferable. Your access links are for your use only.</li>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> Fair use limits apply (per-lesson and daily conversation caps) to keep the service available for everyone.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Acceptable use</h2>
            <p style={{ color: 'var(--muted)' }}>You agree not to:</p>
            <ul className="mt-3 space-y-2" style={{ color: 'var(--muted)' }}>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> Share your access link or account credentials with others</li>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> Attempt to bypass lesson gates or access controls</li>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> Use the platform in any way that could harm AIGA LLC or other users</li>
              <li className="flex gap-2"><span style={{ color: 'var(--accent)' }}>—</span> Reproduce or distribute course content without written permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">AI-generated content</h2>
            <p style={{ color: 'var(--muted)' }}>
              Gojo&apos;s responses are generated by an AI (Claude by Anthropic). While we design Gojo&apos;s behavior carefully, AI can make mistakes. Nothing Gojo says constitutes professional advice of any kind. Use your own judgment when applying what you learn.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Termination</h2>
            <p style={{ color: 'var(--muted)' }}>
              AIGA LLC reserves the right to terminate or suspend access to any account that violates these terms, without notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Limitation of liability</h2>
            <p style={{ color: 'var(--muted)' }}>
              Operator is provided &quot;as is.&quot; AIGA LLC is not liable for any indirect, incidental, or consequential damages arising from your use of the platform. Our total liability to you will not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Governing law</h2>
            <p style={{ color: 'var(--muted)' }}>
              These terms are governed by the laws of the State of Hawaii. Any disputes will be resolved in the courts of Honolulu County, Hawaii.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Changes to these terms</h2>
            <p style={{ color: 'var(--muted)' }}>
              We may update these terms from time to time. We will notify existing members by email if we make material changes. Continued use of the platform after notification constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold mb-3">Contact</h2>
            <p style={{ color: 'var(--muted)' }}>
              AIGA LLC<br />
              Kapolei, Hawaii<br />
              support@buildyouroperator.com
            </p>
          </section>

        </div>
      </article>

      <footer className="max-w-3xl mx-auto px-6 py-10 flex items-center justify-between border-t" style={{ borderColor: 'var(--border)' }}>
        <Link href="/" className="text-sm font-semibold tracking-[0.2em] uppercase" style={{ color: 'var(--accent)', textDecoration: 'none' }}>Operator</Link>
        <div className="flex items-center gap-6 text-xs" style={{ color: 'var(--muted)' }}>
          <Link href="/privacy" style={{ color: 'var(--muted)', textDecoration: 'none' }}>Privacy</Link>
          <Link href="/faq" style={{ color: 'var(--muted)', textDecoration: 'none' }}>FAQ</Link>
          <span>© 2026 AIGA LLC</span>
        </div>
      </footer>
    </main>
  )
}
